export { default as SignUp } from "./Signup"
export { default as Home} from "./Home"
export { default as Login} from "./Login"
export { default as CreatePost} from "./CreatePost"
export { default as EditPost} from "./EditPost"